import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className="w-[320] ml-auto mt-0 mr-auto mb-0 p-[15] md:w-[768] xl:w-[1280]  ">
          {children}
        </div>
        <div className="modal"></div>
      </body>
    </html>
  );
}
